#!/bin/bash -x

sleep 1

i3-msg 'workspace 1; move workspace to output eDP-1'
i3-msg 'workspace 2; move workspace to output eDP-1'
i3-msg 'workspace 3; move workspace to output DP-4'
i3-msg 'workspace 4; move workspace to output DP-4'
i3-msg 'workspace 5; move workspace to output DP-5'
i3-msg 'workspace 6; move workspace to output DP-5'

i3-msg 'workspace 1'

i3-msg restart
